sudo: required

services:
  - docker

before_install:
  - docker pull cmungall/osk

# command to run tests
script: travis_wait 45 cd src/ontology && ./run.sh make travis_test

### Add your own lists here
### See https://github.com/INCATools/ontology-starter-kit/issues/35
notifications:
  email:
    - obo-ci-reports-all@groups.io
