## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/obophenotype for details

# this gives us extra memory:
sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

before_script:
  - cd src/ontology

script:
  - ./run.sh make travis_test
